kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ha-volumestore
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /var/local/k8s-store/ha-config
volumeBindingMode: WaitForFirstConsumer